name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-test:
    strategy:
      matrix:
        python-version: [ '3.9' ]
        os: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip'

      - name: Install 
        run: pip install -r requirements.txt
